project:
  type: book
  output-dir: docs

crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —     # (default is ":")

book:
  title: "Skript Mathematik"
  subtitle: "Der kleine Leitfaden"
  author: "Prof. Dr. Jochen Kruppa"
  date: "04. October 2023"
  chapters:
    - index.qmd
    - literature.qmd
    - preface.qmd
    - part: geometry-preface.qmd
      chapters:
      - geometry-unit.qmd
      - geometry-area.qmd
      - geometry-volume.qmd
    - part: vector-preface.qmd
      chapters: 
      - vector-basic.qmd
      - matrix-basic.qmd
    - part: functions-preface.qmd
      chapters: 
      - functions-basic.qmd
      - functions-extrem-stamm.qmd
    - part: probability-preface.qmd
      chapters:
      - probability-basic.qmd
      - probability-distribution.qmd
    - part: zinsen-preface.qmd
      chapters: 
      - zins-basic.qmd

bibliography: references.bib
lang: de 

format:
  html:
    theme:
      light: zephyr
      dark: superhero
    cover-image: cover2023.png
    mermaid:
      theme: default
#  pdf:
#    documentclass: scrreprt


