project:
  type: book
  output-dir: docs

crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —     # (default is ":")

book:
  title: "Skript Mathematik"
  author: "Prof. Dr. Jochen Kruppa"
  date: "23. February 2023"
  cover-image: cover.png
  chapters:
    - index.qmd
    - literature.qmd
    - preface.qmd
    - part: geometry-preface.qmd
      chapters:
      - geometry-unit.qmd
      - geometry-area.qmd
      - geometry-volume.qmd
    - part: vector-preface.qmd
      chapters: 
      - vector-basic.qmd
      - matrix-basic.qmd
    - part: probability-preface.qmd
#      chapters:
#      - probability-basic.qmd
#      - probability-conditional.qmd
#      - probability-distribution.qmd
    - part: functions-preface.qmd
#      chapters: 
#      - functions-basic.qmd
#      - functions-distance.qmd
#      - matrix-eigenwerte.qmd
      
bibliography: references.bib
lang: de 

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreprt


