project:
  type: book
  output-dir: docs

crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —     # (default is ":")

book:
  title: "Mathematik für Agrarwissenschaften"
  subtitle: "Der kleine Leitfaden"
  author: "<a href='https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/'>Prof. Dr. Jochen Kruppa-Scheetz</a>"
  date: "25. June 2024"
  description: Eine Formelsammlung für Mathematik in den Agrarwissenschaften
  url: https://jkruppa.github.io/math
  repo-url: https://github.com/jkruppa/jkruppa.github.io/math
  repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  search: true
  page-footer:
    left: |
      Mathematik wurde von <a href="https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/">Jochen Kruppa-Scheetz</a> geschrieben. 
    right: |
      Dieses Openbook wurde mit <a href="https://quarto.org/">Quarto</a> erstellt.
  chapters:
    - index.qmd
    - part: geometry-preface.qmd
      chapters:
      - geometry-unit.qmd
      - geometry-area.qmd
      - geometry-volume.qmd
    - part: vector-preface.qmd
      chapters: 
      - vector-basic.qmd
      - matrix-basic.qmd
    - part: functions-preface.qmd
      chapters: 
      - functions-basic.qmd
      - functions-extrem-stamm.qmd
    - part: probability-preface.qmd
      chapters:
      - probability-basic.qmd
      - probability-distribution.qmd
    - part: zinsen-preface.qmd
      chapters: 
      - zins-basic.qmd
    - part: abspann.qmd

bibliography: references.bib
lang: de 

format:
  html:
    theme:
      light: zephyr
      dark: superhero
    cover-image: cover2024.png
    code-annotations: hover
    lightbox: true
    toc-expand: 2
    code-fold: true
    highlight-style: tango
    code-block-border-left: true
    code-summary: "R Code [zeigen / verbergen]"
    code-tools: true
    mermaid:
      theme: neutral
  pdf:
    documentclass: scrreprt


