project:
  type: book
  output-dir: docs

crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —     # (default is ":")

book:
  title: "Skript Mathematik"
  author: "Prof. Dr. Jochen Kruppa"
  date: "11. October 2022"
  link-citations: yes
  cover-image: cover.png
  #downloads: [pdf]
  #page-footer: 
  #  left: "Copyright 2022, Jochen Kruppa" 
  #  right: 
  #    - icon: github
  #      href: https://github.com/jkruppa
  #    - icon: youtube 
  #      href: https://www.youtube.com/c/JochenKruppa
  chapters:
    - index.qmd
    - literature.qmd
    - preface.qmd
    - part: geometry-preface.qmd
      chapters:
      - geometry-unit.qmd
      - geometry-area.qmd
      - geometry-volume.qmd
      - geometry-parts.qmd
    - part: probability-preface.qmd
      chapters:
      - probability-basic.qmd
      - probability-conditional.qmd
      - probability-distribution.qmd
    - part: functions-preface.qmd
      chapters: 
        - functions-basic.qmd
      
bibliography: references.bib
lang: de 

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


