# Einführung {#sec-intro}

*Version vom `r format(Sys.time(), '%B %d, %Y um %H:%M:%S')`*

In diesem Kapitel nenne ich die wichtigsten Lernziele, die nach dem Lesen des Skriptes im Rahmen deiner Lehrveranstaltung von dir erreicht worden sein sollten. Je nach besuchten Kurs kann natürlich nicht *alles* geschafft worden sein. Viele Kapitel haben noch eine Abschnitt in dem du mehr über die Klausur erfährst. So sehe diese Übersicht als Einführung für das was später an Lehrinhalten kommt. Wenn du die Lernziele hier verstehst, dann hast du eine gute und solide Grundlage in Statistik und Bio Data Science. Damit solltest du dann auch gut durch deine Bachelorarbeit kommen.

## Lernziel 1: Geometrische Berechnungen für die Versuchsplanung durchführen

Wir wollen nochmal lernen, wie wir Berechnungen für Flächen durchführen. Wir brauchen das Wissen um später ausrechnen zu können wie viel Platz wir für einen Versuch brauchen. Dafür wiederholen wir nochmal die gängigsten Formen und Flächen. Ebenso berechnen wir die Volumen von den gänigsten Körpern. Das Wissen brauchen wir um Abschätzen zu können wie viel Torf wir für unsere Töpfe ansetzen müssen oder wie viel Futter wir für unser Tierexperiment einkaufen müssen.

## Lernziel 2: Grundlagen von Wahrscheinlichkeiten verstehen

Wir wollen lerne, wie sich Wahrscheinlichkeiten zusammensetzen. Also was ist eigentlich eine Wahrscheinlichkeit, wo kommt die Wahrscheinlichkeit her und wie rechnen wir mit Wahrscheinlichkeiten. Darüber hinaus lernen wir auch die bedingte Wahrscheinlichkeit kennen, die wir später in der Statistik nochmal brauchen. Vieles wirst du wiedererkennen. Wir wollen es hier nochmal wiederholen und festigen. 

## Lernziel 3: Wahrscheinlichkeitsverteilungen verstehen

Neben den einfachen Wahrscheinlichkeiten von einem Ereignis, können wir uns auch kompliziertere Wahrscheinlichkeiten vorstellen. Wir schauen uns nicht nur ein Ereignis an, sondern eben eine ganze Reihe von möglichen Ausgängen eines Zufallsprozesses. Daher werden wir hier nochmal die gänigsten Verteilungen wiederholen und uns anschauen, was eigentlich eine Dichtefunktion ist. 

## Lernziel4: Matrixrechnungen durchführen können

Am Ende wollen wir uns nochmal die Berechnung der Vektor- und Matrixrechnungen anschauen. Wir brauchen die Grundidee der Vektor- und Matrixrechnung in der Statistik um dort mit Vektoren und dann auch Datensätzen rechnen zu können. Wir halten hier aber alles sehr einfach und konzentrieren uns auf das Wichtigste.