```{r echo = FALSE}
pacman::p_load(tidyverse, readxl, knitr, kableExtra, Hmisc)
```

# Berechnungen mit Zinsen {#sec-zins}

*Letzte Änderung am `r format(fs::file_info("zins-basic.qmd")$modification_time, '%d. %B %Y um %H:%M:%S')`*

> *"Compound interest is the eighth wonder of the world. He who understands it, earns it ... he who doesn't ... pays it." --- Albert Einstein*

Das folgende Kapitel basiert auf der [Zinsrechnung auf Wikipedia](https://de.wikipedia.org/wiki/Zinsrechnung). Ich habe hier die teile, die wir dann in der Vorlesung brauchen rausgesucht und angepasst. Deshalb habe ich auch die Notation der Wikipediaseite beibehalten, dann kannst du dort noch mal tiefer Einsteigen, solltest du noch mehr Zinsrechnung in anderen Modulen brauchen. Wir nutzen hier die Grundlagen der Zinsrechnung. Für alle Abschnitte ergibt sich daher eine Notation, die ich hier nochmal vorstelle.

- *Anfangskapital*: $K_0$ (Kapital nach 0 Jahren), das Geld mit dem wir starten. Oder den Kredit, den wir bei der Bank aufnehmen.
- *Endkapital*: $K_n$ (Kapital nach $n$ Jahren), unser Zielbetrag. Wieviel Geld erhalten wir nach den Zinsen und der Laufzeit? Welchen Kredit müssen wir am Ende abbezahlen?
- *Laufzeit (ganze Jahre)*: $n$ Eingabe in Jahren, die Laufzeit unseres Spar- oder Kreditvertrags in Jahren.
- *Zinssatz in Prozent*: $p$ (pro Zinsperiode), die eigentlichen Zinsen, die wir pro Laufzeit erhalten also zum Beispiel $6\%$ Zinsen pro Jahr.
- *Zinssatz als Dezimalangabe*: $i = \tfrac{p}{100}$ (pro Zinsperiode), wenn wir unsere Zinsen nicht in Prozent sondern in einer Dezimalzahl angeben. Also statt $6\%$ Zinsen eben $0.06$ Zinsen.
- *Zinssatz als Zinsfaktor*: $q = 1 + i = 1 + \tfrac{p}{100}$ (pro Zinsperiode), wenn wir unsere Zinsen als einen Faktor übersetzen um zukünftige Beträge zu berechnen. In unserem Beispiel ist der Faktor $q = 1.06$.

Leider ist hier wieder eine Doppelbelegung von verschiedenen Buchstaben und Symbolen. Aber das lässt sich dann leider nicht vermeiden. Wenn ich hier die Buchstaben ändere, dann kommst du später ins Straucheln. Auch für mich ist es immer anstrgend sich alles neu für einen Bereich zu merken.

## Jährliche Verzinsung

Beginnen wir mit der jährlichen Verzinsung. Bei Krediten und Spareinlagen ist die jährliche Verzinsung ja der Standard. Deshalb einmal die lineare Variante ohne die Zinseszins und dann einmal die exponentielle Verzinsung mit dem Zinseszins.

### Einfache Zinsen ohne Zinseszinsen (lineare Verzinsung)

Fangen wir einmal mit der einfachen Formel für lineare Zinsen ohne Zinseszinsen an. Wir wollen wissen wie viel $K_n$ wir aus $K_0$ mit einem Zinssatz $i$ über $n$ Jahre erhalten.

$$
K_n = K_0 + K_0 \cdot n \cdot i = K_0 \cdot (1 + n \cdot i)
$$

Machen wir das Ganze einmal mit einem Beispiel. Wir haben ein Startkapital von 1.000 EUR, welches zu einem Zinssatz von 5 Prozent über 2 Jahre angelegt wird. Bei einfacher Verzinsung ergäbe sich ein damit ein Endkapital wie folgt. Wir wollen also unser Endkapital $K_2$ nach zwei Jahren wissen.

$$
K_2 = 1000 \; \mbox{EUR}  \cdot (1 + 2 \cdot 0.05) = 1100 \; \mbox{EUR} 
$$
Damit kommen wir recht schnell und intuitiv auf unsere $1100$ EUR. Problem ist nur, so wird nicht verzinst. Wir leben in einer Welt des Zinseszins, wie Einstein schon in dem Eingangszitat so schön formuliert hat.

### Zinseszinsrechnung (exponentielle Verzinsung)

Wenn wir den Zinseszins mit berücksichtigen, dann ändert sich die Formel leicht. Wir haben jetzt eine Exponentialfunktion. Wir müssen also nur etwas anders rechnen. Das Setting ist wiederum das Gleiche, wir rechnen wieder mit einem Startkapital von 1.000 EUR, welches zu einem Zinssatz von 5 Prozent über 2 Jahre angelegt wird.

$$
K_n = K_0 \cdot (1 + i)^n = K_0 \cdot q^n
$$

Dann einmal rein mit den Informationen in die Formel und schon erhalten wir unser Endkapitel nach zwei Jahren mit Zinseszins. Hier können wir uns aussuchen, ob wir mit der $i$-Formel oder der $q$-Formel rechnen. 

$$
K_2 = \overbrace{1000 \; \mbox{EUR} \cdot (1 + 0.05)^2}^{K_0 \cdot (1 + i)^n} = \underbrace{1000 \; \mbox{EUR} \cdot (1.05)^2}_{K_0 \cdot q^n}  = 1102.50 \; \mbox{EUR}
$$

Der Betrag ist natürlich hier mit $2.5$ EUR sehr klein. Das macht sich aber bei größeren Beträgen und vorallem längeren Laufzeiten sehr stark bemerkbar! Deshalb schauen wir uns auch gleich einmal die 72er-Regel an.

## 72er-Regel

Die [72er-Regel](https://de.wikipedia.org/wiki/72er-Regel) ist eigentlich eine wunberbare Regel, die es sehr schön erlaubt einmal abzuschätzen, wie gut sich eine Wertanlage lohnt. Die 72er-Regel beschreibt die Zeit $t$ (in Jahren), in der sich eine Kapitalanlage mit Zinssatz $i$ (pro Jahr) verdoppelt. Damit können wir für die 72-Regel wie folgt schreiben. Dabei bezeichnet $p$ die Zinsen in Prozent.

$$
t \approx \frac{72}{100 \cdot i} = \frac{72}{p} ~\text{Jahre}
$$ 

Wir können die Formel auch benutzen, um abzuschätzen, welche Prozentsatz $p$ benötigt wird, um ein Kapital in vorgegebener Zeit $t$ zu verdoppeln.

$$
p \approx \frac{72 ~\text{Jahre}}{t}
$$

Damit kommen wir aucn schon zu dem Beispiel. In welcher Zeit $t$ wird sich eine Wertanlage, der zu einem Prozentsatz von $p = 8$ (8 Prozent pro Jahr) angelegt ist, verdoppeln?

$$
t = \frac{72}{p} ~\text{Jahre} = \frac{72}{8} ~\text{Jahre} = 9 ~\text{Jahre}
$$

Welche Zinsen in Prozent $p$ (pro Jahr) benötigen wir, um ein Kapital im Zeitraum $t=12 ~\text{Jahre}$ zu verdoppeln?

$$
p = \frac{72 ~\text{Jahre}}{t} = \frac{72 ~\text{Jahre}}{12 ~\text{Jahre}} = 6 ~\text{Jahre}
$$

Die 72er-Regel können wir nicht nur auf die Zinsrechnung, sondern auf jede Art exponentiellen Wachstums anwenden. Beispielsweise beträgt die Generationszeit, also die Zeitspanne, in der sich eine Mikrobenpopulation verdoppelt, bei einer stündlichen Wachstumsrate von $4\%$ ungefähr $\tfrac{72}{4}=18$ Stunden.

## Unterjährige Verzinsung

Manchmal haben wir das Problem, dass eine Wertanlage oder ein Kredit nicht ganzjährig läuft. Dann müssen wir mit unterjähriger Verzinsung rechnen. Bei unterjährig verzinslichen Anlagen erfolgt die Zinsgutschrift mehrmals im Jahr oder aber der Kredit läuft nur eine bestimmte Anzahl an Monaten. Der Zeitraum der Verzinsung ist also kleiner als ein Jahr. Üblich sind beispielsweise Zeiträume von:

- einem halben Jahr,
- einem Quartal oder
- einem Monat oder
- tageweise bei Restmonaten.

Die Anzahl der Zinsperioden im Jahr wird in Formeln durch das Symbol $m$ ausgedrückt. Bei quartalsweiser Verzinsung wäre $m$ zum Beispiel 4 also 4 Quartale pro Jahr. Oftmals wird daher ein sogenannter *nomineller Jahreszinssatz* ($i_\mathrm{nom}$) angegeben. Der relative Periodenzinssatz $i_\mathrm{rel}$ beträgt dann:

$$
i_{\mathrm{rel}} = \frac{i_{\mathrm{nom}}}{m}
$$

Wir werden uns die Sachlage dann einmal an ein paar Beispielen anschauen, dann werden die Zusammenhänge dann auch meist klarer.

### Einfache Verzinsung (linear) 

Fangen wir wieder mit einem linearen Zusammenhang an. Wir haben das Endkapital $K_{n,k}$ nach $n$ Jahren mit je $m$ Zinsperioden sowie $k$ weiteren unterjährigen Zinsperioden vorliegen. Damit gilt dann die folgende Formel für das Endkapital.

$$
K_{\mathrm{n,k}} = K_0 \cdot (1 + [n \cdot m + k]\cdot i_{\mathrm{rel}})
$$

Dabei stellt $n \cdot m + k$ die Gesamtzahl von Zinsperioden nach $n$ Jahren und $k$ Perioden dar. Schauen wir uns das einmal mit einem Zahlenbeispiel an. Ein Kapital von 1.000 EUR wird bei monatlicher Verzinsung ($m = 12$) zu einem nominellen Jahreszinssatz von 6 Prozent angelegt. Der relative Prozentsatz $i_\mathrm{rel}$ beträgt daher 0.5%. Nach 2 Jahren und 4 Monaten ergibt sich mit einfachen Zinsen ein Endkapital von 1140 EUR.

$$
K_{\mathrm{2,4}} = 1000 \; \mbox{EUR}  \cdot (1 + [2 \cdot 12 + 4]\cdot 0.005) = 1000 \; \mbox{EUR}  \cdot 1140 = 1140 \; \mbox{EUR}
$$

Die Rechnung ist dabei relativ geradeaus. Du musst eben nur schauen, dass du die Jahre und Monate richtig berücksichtigst. 

### Verzinsung mit Zinseszinsen (exponentiell)

Die lineare Betrachtung macht eigentlich keinen tieferen Sinn. Wir arbeiten eigentlich nur mit dem Zinseszins. Hier haben wir das Endkapital $K_{n,k}$ nach $n$ Jahren mit je $m$ Zinsperioden sowie $k$ weiteren unterjährigen Zinsperioden vorliegen. Die Laufzeit in Zinsperioden berechnet sich also analog zur einfachen Zinsrechnung wieder zu $n \cdot m + k$. Damit gilt dann folgende Formel für das exponentielle Wachstum der Anlage.

$$
K_{\mathrm{n,k}} = K_0 \cdot (1 + i_{\mathrm{rel}})^{n \cdot m + k}
$$
Zusätzlich zum *relativen* und *nominellen* Zinssatz lässt sich beim Zinseszinsfall der *effektive Jahres*zinssatz $i_\mathrm{eff}$ bestimmen, bei dem eine einmalige jährliche Verzinsung zu eben diesem Zinssatz dasselbe Ergebnis liefert wie eine mehrmalige unterjährige Verzinsung zum *relativen* Zinssatz. Wir berechnen dann den effektiven Jahreszins wie folgt.

$$
i_{\mathrm{eff}} = \left( 1 + \frac{i_{\mathrm{nom}}}{m} \right)^m - 1
$$

Auch hier einmal ein Beispiel. Ein Kapital von 1.000 EUR wird wie oben angelegt $(m = 12$; $i_\mathrm{nom} = 6\%$; $i_\mathrm{rel}= \tfrac {0.06} {12} = 0.005$. Nach 2 Jahren und 4 Monaten und damit 28-maliger exponentieller Verzinsung mit dem relativen Periodenzinssatz $i_{\mathrm{rel}}$ beträgt das Kapital inkl. der Zinseszinsen dann 1149.87 EUR.

$$
K_{\mathrm{2,4}} = 1000 \; \mbox{EUR} \cdot (1 + 0.005)^{2 \cdot 12 + 4} \approx 1149.87 \; \mbox{EUR}
$$

Dasselbe Resultat erhielte man aber auch, wenn man von vornherein mit dem effektiven Jahreszinssatz rechnen würde.

$$
i_{\mathrm{eff}} = \left( 1 + \frac{0.06}{12} \right)^{12} - 1 \approx 0.061678 \approx 6.1678\% 
$$

Dann ändert sich die Formel nur leicht und wir erhalten aber das gleiche Ergebnis.

$$
K_{\mathrm{2,4}} = 1000 \; \mbox{EUR} \cdot (1 + 0.061678)^{\frac{28}{12}} \approx 1149.87 \; \mbox{EUR}
$$


